import {Platform, StyleSheet} from 'react-native';
import {getStatusBarHeight, ifIphoneX} from 'react-native-iphone-x-helper';
import {COLORS, hp, wp} from '~app/constants/styles';

/**
 * Styles which can be used in multiple places must be defined here.
 */
export const commonStyles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.WHITE,
    ...ifIphoneX(
      {
        marginTop: getStatusBarHeight() + 24,
      },
      {
        marginTop: Platform.select({
          ios: 14,
          android: 0,
        }),
        paddingTop: hp(24),
      },
    ),
  },
  flex_1: {flex: 1},
  flexRow: {flexDirection: 'row'},
  flexWrap: {flexWrap: 'wrap'},
  flexColumn: {flexDirection: 'column'},
  flexColumnReverse: {flexDirection: 'column-reverse'},
  alignSelfStart: {alignSelf: 'flex-start'},
  alignSelfEnd: {alignSelf: 'flex-end'},
  alignSelfStretch: {alignSelf: 'stretch'},
  alignSelfCenter: {alignSelf: 'center'},
  alignItemsCenter: {alignItems: 'center'},
  alignItemsEnd: {alignItems: 'flex-end'},
  justifyContentBetween: {justifyContent: 'space-between'},
  justifyContentCenter: {justifyContent: 'center'},
  justifyContentEnd: {justifyContent: 'flex-end'},
  justifyContentStart: {justifyContent: 'flex-start'},
  justifyContentSpaceEvenly: {justifyContent: 'space-evenly'},
  center: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerContainer: {
    alignItems: 'center',
    alignContent: 'stretch',
  },
  uploadContainer: {
    height: hp(60),
    width: wp(200),
    borderRadius: 10,
    borderWidth: 1,
    alignSelf: 'center',
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginTop: wp(120),
  },
  quizCard: {
    height: hp(227),
    width: wp(350),
    borderRadius: 10,
    backgroundColor: COLORS.LIGHT_WHITE,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginTop: wp(18),
  },
  resultCard: {
    height: hp(40),
    width: wp(170),
    borderRadius: 6,
    marginTop: wp(10),
  },
  backIcon: {
    position: 'absolute',
    top: 20,
    left: 30,
    width: wp(9),
    height: hp(15),
    color: COLORS.BLACK,
  },
  labelH1: {
    fontSize: 50,
    fontWeight: '400',
    color: COLORS.BLACK,
  },
  labelH2: {
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 25,
  },
  labelH3: {
    fontSize: hp(35),
    fontWeight: '400',
    color: COLORS.BLACK,
  },
  errorLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.READ,
    marginLeft: wp(2),
  },
  inactive: {
    backgroundColor: COLORS.WHITE,
    shadowOpacity: 0.1,
    elevation: 3,
  },
  viewBar: {},
  noMargin: {marginTop: 0, marginBottom: 0, marginLeft: 0, marginRight: 0},
  noPadding: {paddingHorizontal: 0, paddingVertical: 0},
  pb_4: {paddingBottom: hp(4)},
  pb_8: {paddingBottom: hp(8)},
  pb_12: {paddingBottom: hp(12)},
  pb_16: {paddingBottom: hp(16)},
  pb_24: {paddingBottom: hp(24)},
  pb_32: {paddingBottom: hp(32)},
  pt_4: {paddingTop: hp(4)},
  pt_8: {paddingTop: hp(8)},
  pt_12: {paddingTop: hp(12)},
  pt_16: {paddingTop: hp(16)},
  pt_24: {paddingTop: hp(24)},
  pt_32: {paddingTop: hp(32)},
  pt_110: {paddingTop: hp(110)},
  pv_4: {paddingVertical: hp(4)},
  pv_8: {paddingVertical: hp(8)},
  pv_12: {paddingVertical: hp(12)},
  pv_16: {paddingVertical: hp(16)},
  pv_24: {paddingVertical: hp(24)},
  pv_32: {paddingVertical: hp(32)},
  ph_4: {paddingHorizontal: wp(4)},
  ph_8: {paddingHorizontal: wp(8)},
  ph_12: {paddingHorizontal: wp(12)},
  ph_16: {paddingHorizontal: wp(16)},
  ph_24: {paddingHorizontal: wp(24)},
  ph_32: {paddingHorizontal: wp(32)},
  pr_10: {paddingRight: wp(10)},
  mb_4: {marginBottom: hp(4)},
  mb_8: {marginBottom: hp(8)},
  mb_12: {marginBottom: hp(12)},
  mb_16: {marginBottom: hp(16)},
  mb_20: {marginBottom: hp(20)},
  mb_24: {marginBottom: hp(24)},
  mb_32: {marginBottom: hp(32)},
  mt_2: {marginTop: hp(2)},
  mt_4: {marginTop: hp(4)},
  mt_8: {marginTop: hp(8)},
  mt_12: {marginTop: hp(12)},
  mt_16: {marginTop: hp(16)},
  mt_24: {marginTop: hp(24)},
  mt_32: {marginTop: hp(32)},
  mt_60: {marginTop: hp(60)},
  mt_40: {marginTop: hp(40)},
  mt_70: {marginTop: hp(70)},
  mt_110: {marginTop: hp(110)},
  mt_130: {marginTop: hp(130)},
  mt_200: {marginTop: hp(200)},
  mt_300: {marginTop: hp(300)},
  ml_4: {marginLeft: wp(4)},

  ml_8: {marginLeft: wp(8)},
  ml_10: {marginLeft: wp(10)},
  ml_12: {marginLeft: wp(12)},
  ml_16: {marginLeft: wp(16)},
  ml_24: {marginLeft: wp(24)},
  ml_32: {marginLeft: wp(32)},
  ml_125: {marginLeft: wp(125)},
  ml_150: {marginLeft: wp(150)},
  ml_155: {marginLeft: wp(155)},
  ml_180: {marginLeft: wp(180)},
  ml_110: {marginLeft: wp(110)},
  mr_4: {marginRight: wp(4)},
  mr_8: {marginRight: wp(8)},
  mr_12: {marginRight: wp(12)},
  mr_16: {marginRight: wp(16)},
  mr_24: {marginRight: wp(24)},
  mr_32: {marginRight: wp(32)},
  mv_4: {marginVertical: hp(4)},
  mv_8: {marginVertical: hp(8)},
  mv_12: {marginVertical: hp(12)},
  mv_16: {marginVertical: hp(16)},
  mv_24: {marginVertical: hp(24)},
  mv_32: {marginVertical: hp(32)},
  mh_4: {marginHorizontal: wp(4)},
  mh_8: {marginHorizontal: wp(8)},
  mh_12: {marginHorizontal: wp(12)},
  mh_16: {marginHorizontal: wp(16)},
  mh_24: {marginHorizontal: wp(24)},
  mh_32: {marginHorizontal: wp(32)},

  txtCenter: {
    textAlign: 'center',
  },

  rotate_10: {transform: [{rotate: '10deg'}]},
  rotate_90: {transform: [{rotate: '90deg'}]},
  rotate_180: {transform: [{rotate: '180deg'}]},
  rotate_170: {transform: [{rotate: '170deg'}]},
  rotate_225: {transform: [{rotate: '225deg'}]},
  rotate_270: {transform: [{rotate: '270deg'}]},

  labelWeightBold: {fontWeight: 'bold'},
  labelWeight400: {fontWeight: '400'},
  labelWeight500: {fontWeight: '500'},
  labelWeight600: {fontWeight: '600'},
  labelWeight700: {fontWeight: '700'},
  labelWeight800: {fontWeight: '800'},

  fs_12: {fontSize: 12},
  fs_16: {fontSize: 16},
  fs_14: {fontSize: 14},
  fs_20: {fontSize: 20},
  fs_28: {fontSize: 28},
  fs_40: {fontSize: 40},

  fw_500: {fontWeight: '500'},
  fw_600: {fontWeight: '600'},
  fw_400: {fontWeight: '400'},

  bgWhite: {backgroundColor: COLORS.WHITE},
  bgLgPurple: {backgroundColor: COLORS.LIGHT_PURPLE},
  bgLgGray: {backgroundColor: COLORS.DISABLED_TEXT},
  bgWine: {backgroundColor: COLORS.WINE},

  blackColor: {
    color: COLORS.BLACK,
  },
  wineColor: {
    color: COLORS.WINE,
  },
});
